Rework forbidden-files hook to reduce checked commits
By looking at the git merge-base, skip existing commits.

diff --git a/src/all-hooks/forbidden-files b/src/all-hooks/forbidden-files
--- a/src/all-hooks/forbidden-files
+++ b/src/all-hooks/forbidden-files
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 
 
 # Check if all new git commits don't contain forbidden files:
@@ -7,46 +7,39 @@
 # - build.specials.obscpio
 
 
-set -eu
+set -euo pipefail
 
 echo "Running hook: $(basename $0)"
 
-if ! which git-lfs &> /dev/null; then
-    echo "ERROR: git-lfs command not found."
-    exit 1
-fi
+while read -r old_rev new_rev ref_name; do
 
+    # Skip on branch deletion.
+    [[ "$new_rev" =~ ^0+$ ]] && continue
 
-while read -r old_oid new_oid ref_name; do
-    # determine if we're creating a new branch - old_oid is all zeros
-    if [[ "${old_oid}" =~ ^0+$ ]]; then
-        new_branch=1
-    else
-        new_branch=0
+    # Handle branch creation.
+    range="${old_rev}..${new_rev}"
+    if [[ "$old_rev" =~ ^0+$ ]]; then
+        range="$new_rev"
     fi
 
-    # list all commits for a new branch or new commits for an existing branch
-    if [ ${new_branch} -eq 1 ]; then
-        new_commits=$(git rev-list "${new_oid}")
-    else
-        new_commits=$(git rev-list "${old_oid}".."${new_oid}")
-    fi
+    # Limit range to only new commits relative to repository history.
+    merge_base=$(git merge-base "${new_rev}" $(git for-each-ref --format='%(objectname)') 2>/dev/null | head -n1 || true)
+    [ -n "$merge_base" ] && range="${merge_base}..${new_rev}"
 
     failed=0
 
     # run check for each new commit
-    for commit in ${new_commits}; do
+    while read -r commit; do
         # forbid .osc anywhere in the directory structure
         matches=$(git show --pretty="" --name-only --diff-filter=A "${commit}" | grep -E '(^|/)(\.osc|_scmsync\.obsinfo|build\.specials\.obscpio)($|/)' || :)
         if [ -n "${matches}" ]; then
-            echo "ERROR: Forbidden file or directory found in commit ${commit}"
-            echo "${matches}"
+            echo "ERROR: Forbidden file or directory found in commit ${commit}" >&2
+            echo "${matches}" >&2
             failed=1
         fi
-    done
+    done < <(git rev-list "${range}")
 
-    if [ ${failed} -eq 1 ]; then
-        echo "Push rejected."
-        exit 1
-    fi
+    [ "$failed" -eq 1 ] && exit 1
 done
+
+exit 0
